/* eslint-disable no-unused-vars */
/* eslint-disable react/prop-types */
import React from "react";
import { Page, Text, View, Document, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  body: {
    paddingTop: 40,
    paddingBottom: 40,
    paddingHorizontal: 50,
    fontFamily: "Helvetica",
  },
  header: {
    fontSize: 14,
    textAlign: "right",
    marginBottom: 30,
    color: "#555",
  },
  title: {
    fontSize: 26,
    textAlign: "center",
    fontWeight: "bold",
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 20,
    fontWeight: "bold",
    marginTop: 25,
    marginBottom: 8,
  },
  text: {
    fontSize: 16,
    marginBottom: 5,
  },
  boldText: {
    fontWeight: "bold",
    fontSize: 17, 
  },
  italicText: {
    fontSize: 16,
    fontStyle: "italic",
    color: "#333", // Darker to stand out
  },
  section: {
    marginBottom: 18,
  },
  table: {
    display: "flex",
    flexDirection: "column",
    marginTop: 8,
    borderWidth: 1,
    borderColor: "#000",
  },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#000",
    paddingVertical: 6,
  },
  tableCell: {
    fontSize: 16, 
    flex: 1,
    textAlign: "center",
    paddingVertical: 4,
  },
  footer: {
    position: "absolute",
    bottom: 20,
    left: 0,
    right: 0,
    textAlign: "center",
    fontSize: 13,
    color: "#888",
  },
});

export default function ReportDocument({
  reportedBuilding,
  reportedRoom,
  reportedPcID,
  comment,
  submittee,
  reportId = "12000",
  partsCondition,
}) {
  return (
    <Document>
      <Page size="A4" style={styles.body}>
        {/* Header */}
        <Text style={styles.header}>Report Type: {"Physical Copy"}</Text>

        {/* Title */}
        <Text style={styles.title}>National University - ITSO</Text>
        <Text style={{ ...styles.text, textAlign: "center", marginBottom: 20 }}>
          Computer Laboratory Management System
        </Text>

        {/* Submittee Information */}
        <View style={styles.section}>
          <Text style={styles.subtitle}>Submittee</Text>
          <Text style={styles.boldText}>{submittee}</Text>
        </View>

        {/* Location Details */}
        <View style={styles.section}>
          <Text style={styles.subtitle}>Location</Text>
          <Text style={styles.text}>
            <Text style={styles.boldText}>Building: </Text>
            <Text style={styles.boldText}>{reportedBuilding}</Text>
          </Text>
          <Text style={styles.text}>
            <Text style={styles.boldText}>Room: </Text>
            <Text style={styles.boldText}>{reportedRoom}</Text>
          </Text>
          <Text style={styles.text}>
            <Text style={styles.boldText}>Computer ID: </Text>
            <Text style={styles.boldText}>{reportedPcID}</Text>
          </Text>
        </View>

        {/* Reported Components (Tabular Format) */}
        <View style={styles.section}>
          <Text style={styles.subtitle}>Reported Components</Text>
          <View style={styles.table}>
            <View style={[styles.tableRow, { backgroundColor: "#ddd" }]}>
              <Text style={styles.tableCell}>
                <Text style={styles.boldText}>Component</Text>
              </Text>
              <Text style={styles.tableCell}>
                <Text style={styles.boldText}>Condition</Text>
              </Text>
            </View>
            {partsCondition
              .filter((pc) => pc.condition)
              .map((pc, i) => (
                <View key={i} style={styles.tableRow}>
                  <Text style={styles.tableCell}>{pc.key}</Text>
                  <Text style={styles.tableCell}>
                    <Text style={styles.boldText}>{pc.condition}</Text>
                  </Text>
                </View>
              ))}
          </View>
        </View>

        {/* Comments & Feedback */}
        <View style={styles.section}>
          <Text style={styles.subtitle}>Comment & Feedback</Text>
          <Text style={styles.italicText}>&quot;{comment}&quot;</Text> 
        </View>

        {/* Footer */}
        <Text style={styles.footer}>Generated by ITSO CLMS v2.0</Text>
      </Page>
    </Document>
  );
}
